name 'rails-stack'

depends 'application'
depends 'application_ruby'
depends 'application_git'
depends 'ruby_build'
depends 'user'
depends 'runit'
depends 'ssh_known_hosts'
depends 'poise-ruby-build'
